### ISSUE TITLE
📦  Omni: v0.34

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#142]
```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/omni/issues/143
- [ ] https://github.com/siderolabs/omni/issues/144
- [ ] https://github.com/siderolabs/omni/issues/145
```
