### ISSUE TITLE
[epic] cluster autoscaling

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#36]
```mermaid
flowchart TD
    BASE("Base Cloud Provider Support in Omni")
    CPLIB("Base Cloud Provider Library")
    QEMU("QEMU Cloud Provider")
    METAL("METAL Cloud Provider")
    TALEMU("Talemu Cloud Provider")
    KUBEVIRT("KubeVirt Cloud Provider")
    MC("Managed Control Planes")
    MP("Machine Pools /manual scaling/")
    MCA("Machine Class auto scaling")
    MSP("MachineSet Machine Class pressure")
    CPI("Cluster Resource Pressure")
    CAA("Cluster Auto Scaling")
    TA("Talos Agent")
    IPMI("IPMI Management")
    HCP("CP MachineSet not managed by the user")
    CPSH("CP Self-healing")
    EQUINIX("Equinix Cloud Provider")
    QEMU --> METAL
    CPLIB --> TALEMU
    CPLIB --> KUBEVIRT
    KUBEVIRT --> MC
    TALEMU --> MP
    MSP --> MCA
    MP --> MCA
    CPI --> CAA
    MCA --> CAA
    TA --> METAL
    IPMI --> METAL
    HCP --> MC
    CPSH --> MC
    BASE --> CPLIB
    CPLIB --> QEMU
    CPLIB --> EQUINIX
```

Done tasks

- [ ] https://github.com/siderolabs/omni/issues/270
- [ ] https://github.com/siderolabs/omni/issues/365
- [ ] https://github.com/siderolabs/omni/issues/501
- [ ] https://github.com/siderolabs/omni/issues/518
- [ ] https://github.com/siderolabs/omni/issues/521
- [ ] https://github.com/siderolabs/omni/issues/366
- [ ] https://github.com/siderolabs/omni/issues/367
- [ ] https://github.com/siderolabs/omni/issues/600
- [x] machine set node controller should support the mode which allocates machines from a specific machine request set
- [ ] https://github.com/siderolabs/omni/issues/595
- [ ] https://github.com/siderolabs/omni/issues/603
- [ ] https://github.com/siderolabs/omni/issues/659
- [ ] https://github.com/siderolabs/omni/issues/662
- [ ] https://github.com/siderolabs/omni/issues/664
