### ISSUE TITLE
Omni Talos 1.8.0 support

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#544]
```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/omni/issues/519
- [ ] https://github.com/siderolabs/omni/issues/54
- [ ] https://github.com/siderolabs/omni/issues/606
- [ ] https://github.com/siderolabs/talos/pull/9275
- [ ] https://github.com/siderolabs/omni/issues/631
```
