### ISSUE TITLE
infrastructure provider path

### ISSUE THREAD

**Issue by smira** [siderolabs/omni#640]
```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/omni/issues/644
- [ ] https://github.com/siderolabs/omni/issues/645
- [ ] Infra provider in Omni (list of key-values that a user can set on the MachineClass)
- [ ] Minimal AWS Infra Provider (for user testing)
- [ ] Cluster template alpha feature: MachineClasses with Infra Providers
- [ ] Delivery point 0: a user runs AWS provider manually, connects to Omni, can provision machines in AWS automatically
- [ ] Potential idea: Minimal Proxmox Infra Provider
- [ ] Potential idea: documentation/skeleton of an Infra Provider
- [ ] Metal Cloud Provider by ripping Sidero Metal into pieces
- [ ] Power management + reboot in Omni Provider API + Omni UI/
- [ ] Delivery point 1: Metal cloud provider
- [ ] Metal Cloud Provider: additional features
- [ ] Omni-hosted cloud providers
- [ ] Omni UI for Machine Classes with infra providers
```

```[tasklist]
### Alternative path
- [ ] Metal Infra provider follows Sidero Metal flow: powers on all machines, they reboot and connect to Omni
- [ ] Omni sees all Metal machines in the Machines view
- [ ] Metal Provider controls the machines - e.g. powers it off, wipes it, etc.
- [ ] We don't need MachineClasses with infra provider, just regular Machine Classes
- [ ] Machine is automatically powered on when used
- [ ] Wipe by the Infra Provider
```
