### ISSUE TITLE
[epic] Omni audit logs

### ISSUE THREAD

**Issue by DmitriyMV** [siderolabs/omni#694]
Split from #37 

## Future ideas

- [ ] Allow user to specify the retention policy
- [ ] Allow user to speciby the `begin` and `end` dates for getting logger
- [ ] Add support for MachineClass resources.
- [ ] Resource deletion should also print associated labels.
- [ ] Log when user downloads `talosconfig`.
- [ ] Log when user downloads `kubeconfig`.
- [ ] Maybe drop `GET` requests from logging k8s access.
- [ ] Compress audit logs after rotation
- [ ] Allow user to forward audit logs to external log receiver (splunk, syslogd, etc)
- [ ] Allow user to see/search audit records directly in Omni web UI

**Comment by steverfrancis** [comment]
I dont think there is any use case for allowing the user to specify the audit retention policy.
As a user, I will just want as much retention as possible.

Rather, I think WE need to specify an audit policy: retention of 30 days events, or X number of events, which ever is smaller.
That way if someone hammers something that causes logs, we aren't on the hook to provide an infinite amount of storage in order to meet 30 days retention.

**Comment by utkuozdemir** [comment]
Closing this, as it was created long ago to track audit logging feature - most of the items in the list are already implemented, and some of them are no more applicable. If we identify gaps, they should be opened as new issues.
