### ISSUE TITLE
[Epic] Bare-Metal Infra Provider

### ISSUE THREAD

**Issue by utkuozdemir** [siderolabs/omni#757]
## Demo

- Start fresh Omni instance
- Create a service account key for the provider using `omnictl`
- Start the provider with correct set of flags and service account key in your subnet
- Boot your bare metal machines
- They pop up in Omni machines screen as "Pending Acceptance"
- Accept some machines
- Go and create a cluster using those machines
- Destroy the cluster
- Machines will be powered off

### Bare-Metal Provider Tasks
```[tasklist]
- [ ] https://github.com/siderolabs/omni/issues/767
- [ ] https://github.com/siderolabs/omni/issues/761
- [ ] https://github.com/siderolabs/omni/issues/768
- [x] Peer-review the provider code
- [ ] https://github.com/siderolabs/omni/issues/769
- [ ] https://github.com/siderolabs/omni/issues/770
- [ ] https://github.com/siderolabs/omni/issues/771
- [x] Talos 1.9.0 release
- [ ] https://github.com/siderolabs/omni/issues/785
```

### Omni UI Tasks
```[tasklist]
- [ ] https://github.com/siderolabs/omni/issues/766
- [ ] https://github.com/siderolabs/omni/issues/773
- [ ] https://github.com/siderolabs/omni/issues/774
- [ ] https://github.com/siderolabs/omni/issues/831
```

## Phase 2

```[tasklist]
- [ ] https://github.com/siderolabs/omni/issues/894
- [ ] https://github.com/siderolabs/omni/issues/813
- [ ] https://github.com/siderolabs/omni/issues/823
- [ ] https://github.com/siderolabs/omni/issues/895
- [ ] https://github.com/siderolabs/omni/issues/896
- [ ] https://github.com/siderolabs/omni/issues/824
- [ ] https://github.com/siderolabs/omni/issues/815
- [ ] https://github.com/siderolabs/omni/issues/820
- [ ] https://github.com/siderolabs/omni/issues/796
- [ ] https://github.com/siderolabs/omni/issues/797
- [ ] https://github.com/siderolabs/omni/issues/798
```

## Phase X

```[tasklist]
- [ ] Provider logs & UI
- [ ] Enable extensions automatically based on PCI devices (non-removable)
- [ ] Global/matcher-based "Preferred Power State" configuration & UI
- [ ] BMC console logs & UI
- [ ] https://github.com/siderolabs/omni/issues/871
- [ ] https://github.com/siderolabs/talos/issues/10209
```
